name: Crypto Scanner Automation

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          cd ..
      
      - name: Run scanner
        run: |
          cd backend
          python scanner.py
          cd ..
      
      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backend/scan_results.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update scan results [skip ci]"
          git push
