name: Crypto Scanner Automation

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create data directories
        run: |
          mkdir -p docs/data
          mkdir -p backend

      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install requests pandas numpy

      - name: Run scanner with timeout protection
        working-directory: ./backend
        run: |
          timeout 300 python scanner.py || echo "Scanner timed out but continuing..."

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/data/
          git diff --cached --quiet || (git commit -m "Update scan results [skip ci]" && git push)
